### PR TITLE
Better support for Bootstrap 3

### PR DESCRIPTION
**Pull request by dgorbash**

### CODE REVIEW

**Comment by mwhitneysdsu** [comment]
@boblennes Any thoughts on these changes?

**Comment by boblennes** [comment]
It's hard to see some of the changes due to whitespace shifts, but I like many of the changes.  However, in the current branch, we purposely left some classes unchanged; eg the -danger suffix as -error to ease migration.  The question is whether to move to follow standard bootstrap3 class name conventions, which @dgorbash has seemingly done a good job of doing, or continue to keep some of the classes in place for a little easier backward compatibility.  My vote is to bring these changes in, although I'd prefer a cleaner pull request without all the white space shifts so people can see what exactly changed all in there. (Btw I noticed one typo in bonfire/modules/migrations/views/developer/index.php line 21 "labelfor").  I've pretty much abandoned use of BS 2.3.2 but I don't know about everyone else.

**Comment by dgorbash** [comment]
@boblennes I'll clean my pull request and update it (remove unnecessary whitespaces, typos and other changes which not belongs to BS3 directly)

**Comment by pascut** [comment]
We should start working at adding integration for CI4 and Bootstrap 4. Anyone interested?

**Comment by cosmomathieu** [comment]
@pascut I'd be happy to help when I have time. However, CI4 has changed so dramatically that I think Bonfire will need to as well. This is a HUGE undertaking!!! Let me know your thoughts.

**Comment by boblennes** [comment]
If you want to incorporate CI4 you wlll want to start from scratch.  If you want to incorporate BS4 that is simpler.  You can look at what I did in Ignition Go ( https://github.com/ci-blox/Ignition-Go ) - I used the same template library from Bonfire.  I would love to port over some of the modules in Bonfire but not enough time.  I hope to create a Bonfire-esque satrter library for CI4, probably once CI4 hits Alpha 2,

**Pull request closed without merging**
