### PR TITLE
Added gravatar default image options on config/application.php

### PR DESCRIPTION
**Pull request by JbalTero**

### CODE REVIEW

**Comment by JbalTero** [comment]
@mwhitneysdsu Is it better if the config is in different config file? Like config/gravatar.php

**Comment by mwhitneysdsu** [comment]
It's probably fine in the application config, but it needs to default to something if `config_item('users.gravatar_default_image')` returns null/false, and it should probably check to make sure the returned value is one of the valid options.

**Comment by JbalTero** [comment]
Done updating.

**Comment by JbalTero** [comment]
@mwhitneysdsu

**Pull request merged**
